### ISSUE TITLE
build and deploy in Travis CI

### ISSUE THREAD

**Issue by terinjokes** [go-kit/go-kit.github.io#10]
Right now to contribute to this repo, the instructions have you edit the files in `_src`, run make to generate the site, then commit both. A contribute has to remember to generate the final output, and the reviewers need to look at both (and check that the html pages are generated from the same markdown revision).

We can change `master` to contain *only* the source files, and use Travis CI's [GitHub Pages Deployment](https://docs.travis-ci.com/user/deployment/pages/) to deploy to the `gh-pages` branch automatically.

I think this would make it easier to contribute to the website, and easier for reviewers to review changes.

I'm happy to make the changes and contribute the `.travis.yml`, if this is something you agree with.

**Comment by peterbourgon** [comment]
+100.

**Comment by terinjokes** [comment]
Per [GitHub's docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) this repo can only publish from the `master` branch, since it matches "*organization*.gihtub.io".

As an alternative, we can have the source files on another branch, and set that branch as the "Default branch". On my fork, the deployment expects this default branch to be "source".

**Comment by peterbourgon** [comment]
I've no opinion on that. Whatever makes it easier for you.
