### ISSUE TITLE
Invalid links under examples/stringsvc.html

### ISSUE THREAD

**Issue by buraksekili** [go-kit/go-kit.github.io#35]
# Bug report

The `stringsvc1`, `stringsvc2`, `stringsvc3`, `addsvc/cmd/addcli` and `package profilesvc/client` links under https://gokit.io/examples/stringsvc.html are pointing to wrong place. 

I saw [this PR](https://github.com/go-kit/go-kit.github.io/pull/33) that updates the `example` links but I guess, https://gokit.io/examples/stringsvc.html is missed. 

## Example screenshot
![image](https://user-images.githubusercontent.com/32663655/125656414-b368bad4-5447-43e4-9d68-8233fb79b9f8.png)

**Comment by peterbourgon** [comment]
I know, the generation pipeline is busted.

**Comment by peterbourgon** [comment]
Fixed properly now.
